#lang eopl
(require racket/include)
(include "safe.rktl")
(define zero        (lambda ()  '()))
(define is-zero?    (lambda (n) (null? n)))
(define successor   (lambda (n) (cons #t n)))
(define predecessor (lambda (n) (cdr n)))
(include "plus.rktl")
(printf "unary plus: ~s\n" (plus '(#t #t) '(#t)))
(printf "unary pred zero: ~s\n" (try (predecessor (zero))))
